/**
 * Every user-visible string. Screens call t(key, vars) and never invent copy.
 * Keys match PRD §7 plus screen strings from PRD §8.
 */
const STRINGS = {
  "tab.dashboard": "Dashboard",
  "tab.grabar": "Grabar",
  "tab.creadoras": "Creadoras",
  "tab.feed": "Feed",
  "nav.back": "Atrás",
  "nav.close": "Cerrar",
  "nav.settings": "Ajustes",
  "nav.note": "Nota",
  "nav.boards": "Boards",
  "nav.sections": "Secciones",
  "status.updated": "Actualizado {ago}",
  "status.updating": "Actualizando…",
  "status.stale": "Sin actualizar desde las {time}",
  "status.failed": "No se pudo actualizar",
  "status.retry": "Reintentar",
  "status.offline": "Sin conexión",
  "status.outbox": "{n} por enviar",
  "banner.update": "Hay una versión nueva",
  "banner.update.cta": "Actualizar",
  "banner.offline": "Sin conexión · datos de {ago}",
  "banner.install.ios": "Instala Comando en tu iPhone",
  "banner.install.cta.ios": "Ver cómo",
  "banner.install.other": "Instala Comando",
  "banner.install.cta": "Instalar",
  "banner.keychanged": "Tu link cambió. Pega el link nuevo del Comando.",
  "banner.keychanged.cta": "Pegar link",
  "banner.creadoras.offline": "Sin conexión: no se pueden revisar tomas",
  "banner.creadoras.failed": "No se pudo actualizar las tomas",
  "banner.nomailbox": "Sin buzón. Pídele a Grok el link nuevo.",
  "common.loading": "Cargando…",
  "common.retry": "Reintentar",
  "common.cancel": "Cancelar",
  "common.done": "Listo",
  "common.undo": "Deshacer",
  "common.seeAll": "Ver todo",
  "common.seeMore": "Ver {n} más",
  "common.seeLess": "Ver menos",
  "common.needOnline": "Necesitas conexión",
  "common.or": "o",
  "common.understood": "Entendido",
  "common.discard": "Descartar",
  "common.keepWriting": "Seguir escribiendo",

  "toast.done": "Listo",
  "toast.picked": "Elegiste {letter} · Grok prepara el board",
  "toast.pickCleared": "Elección quitada",
  "toast.filmed": "Marcado como grabado",
  "toast.unfilmed": "Desmarcado",
  "toast.want": "Anotado · sale en Productos en el próximo refresh",
  "toast.noteSent": "Nota enviada",
  "toast.noteQueued": "Nota guardada · se envía al volver la conexión",
  "toast.copied.link": "Link copiado",
  "toast.copied.script": "Guion copiado",
  "toast.copied.search": "Búsqueda copiada · abre Gmail, toca Buscar y pega",
  "toast.copyFailed": "No se pudo copiar",
  "toast.extended": "Extendido 3 días · vence {when}",
  "toast.revoked": "Link revocado",
  "toast.approved": "Toma aprobada",
  "toast.redo": "Pediste re-grabar",
  "toast.go": "GO enviado",
  "toast.changes": "Cambios pedidos",
  "toast.actionFailed": "No se pudo. Prueba otra vez.",
  "toast.needOnline": "Necesitas conexión",
  "toast.uploadDone": "Video subido",
  "toast.feedNeedLink": "Abre el link del feed una vez para agregarlo",
  "toast.shared": "Listo para compartir",

  "err.incomplete.title": "Link incompleto",
  "err.incomplete.body": "Pídele a Grok el link completo.",
  "err.host.title": "Abre este link desde jorgedearmas.github.io",
  "err.host.body": "",
  "err.decrypt.title": "No se pudo abrir",
  "err.decrypt.body": "Si el link es nuevo, espera un minuto.",
  "err.offlineFirst.title": "Sin conexión",
  "err.offlineFirst.body": "Conéctate para abrir por primera vez.",
  "err.keyChanged.title": "Tu link cambió",
  "err.keyChanged.body": "Pega el link nuevo del Comando.",
  "err.portalInactive.title": "Este link ya no está activo",
  "err.portalInactive.body": "Pídele uno nuevo a Jorge.",
  "err.boardOpen.title": "No se pudo abrir el board",
  "err.boardOpen.body": "",
  "err.generic.title": "Algo falló",
  "err.generic.body": "",

  "up.section": "Subir video",
  "up.hint": "Graba en 1080p, vertical",
  "up.button": "Subir video",
  "up.resume": "Reanudar",
  "up.take": "Escena {shot} · Toma {take}",
  "up.stay": "No cierres la app mientras sube. Si se corta, vuelve y toca Reanudar.",
  "up.stay.portal": "No cierres Safari mientras sube. Si se corta, vuelve a abrir este link y toca Reanudar.",
  "up.onlyVideo": "Solo se pueden subir videos.",
  "up.inactive": "Este link ya no está activo.",
  "up.closed": "Esta toma ya está cerrada.",
  "up.startFailed": "No se pudo empezar. Revisa la conexión y prueba otra vez.",
  "up.cut": "Se cortó la subida. Toca Reanudar.",
  "up.pickSame": "Elige el mismo video para seguir.",
  "up.notSame": "Ese no es el mismo video.",
  "up.restart": "Empezar de nuevo",
  "up.resuming": "Reanudando…",
  "up.needOnline": "Necesitas conexión para subir.",
  "up.redoBanner": "Re-grabar: {reason}",
  "up.approve": "Aprobar",
  "up.go": "GO",
  "up.changes": "Pedir cambios",

  "empty.todo.title": "Nada por hacer",
  "empty.todo.body": "Grok sigue trabajando.",
  "empty.products.title": "Ningún producto elegido",
  "empty.products.body": "En el Feed toca «Lo quiero» o mándale el link a Grok.",
  "empty.brands.title": "Sin tratos abiertos",
  "empty.brands.body": "",
  "empty.grabar.todo.title": "¡Todo grabado!",
  "empty.grabar.todo.body.owner": "Sube las tomas desde cada board.",
  "empty.grabar.todo.body.mac": "Pasa las tomas a la Mac.",
  "empty.grabar.done.title": "Nada grabado todavía",
  "empty.grabar.done.body": "Cuando marques un video, sale aquí.",
  "empty.creadoras.title": "Ninguna creadora activa",
  "empty.creadoras.body": "Pídele a Grok un link para una creadora.",
  "empty.review.title": "Nada por revisar",
  "empty.review.body": "",
  "empty.boards.title": "No hay boards",
  "empty.boards.body": "",
  "empty.boards.lane.title": "No hay boards de {lane}",
  "empty.boards.lane.body": "",
  "empty.feed.filter.title": "No hay videos con este filtro",
  "empty.feed.filter.body": "Toca Filtros para cambiarlo.",
  "empty.portal.title": "Nada que grabar",
  "empty.portal.body": "",

  "onb.title": "Comando",
  "onb.lead": "Pega el link del Comando que te mandó Grok.",
  "onb.paste": "Pegar link",
  "onb.opening": "Abriendo…",
  "onb.or": "o",
  "onb.placeholder": "Pega aquí el link…",
  "onb.open": "Abrir",
  "onb.hint": "El link se guarda solo en este teléfono.",
  "onb.hold": "Mantén presionado aquí y toca Pegar.",
  "onb.err.nourl": "Eso no parece un link. Pega el link completo del Comando.",
  "onb.err.single": "Ese link es de una sola página. Pega el link del Comando.",
  "onb.err.creator": "Ese es un link de creadora. Pega el link del Comando.",
  "onb.err.key": "La llave no abre el Comando. Pídele el link a Grok de nuevo.",
  "onb.err.offline": "Sin conexión. Conéctate para abrir por primera vez.",

  "dash.hero.next": "LO PRÓXIMO",
  "dash.hero.filmToday": "Grabar hoy",
  "dash.hero.filmOverdue": "Grabación atrasada",
  "dash.hero.filmMeta": "{n} videos · {places}",
  "dash.hero.goGrabar": "Ir a Grabar",
  "dash.hero.reviewOne": "Revisar tomas de {name}",
  "dash.hero.reviewMany": "Revisar tomas",
  "dash.hero.reviewMeta": "{n} tomas nuevas",
  "dash.hero.reviewCta": "Revisar",
  "dash.hero.expiring": "El link de {name} vence hoy",
  "dash.hero.expiringMeta": "{n} productos sin terminar",
  "dash.hero.extend": "Extender 3 días",
  "dash.hero.allGood": "Todo al día",
  "dash.hero.allGoodMeta": "Grok sigue trabajando.",
  "dash.todo": "Por hacer",
  "dash.products": "Productos",
  "dash.brands": "Marcas",
  "dash.grok": "Grok trabaja en",
  "dash.alerts": "Avisos",
  "dash.seeAllN": "Ver todos ({n})",
  "dash.feed": "Feed",
  "dash.boards": "Boards",
  "dash.feed.today": "{n} videos hoy",
  "dash.feed.updated": "Actualizado {when}",
  "dash.feed.loading": "Cargando…",
  "dash.feed.needKey": "Ábrelo una vez desde su link",
  "dash.boards.problem": "{n} con problema",
  "dash.boards.count": "{n} boards",
  "dash.tile.open": "Toca para abrir",
  "dash.group.overdue": "ATRASADO",
  "dash.group.undated": "SIN FECHA",
  "dash.openFeed": "Abrir feed",

  "act.pick": "Elegir guion",
  "act.publish": "Publicado",
  "act.done": "Hecho",
  "act.reply": "Responder",
  "act.review": "Revisar",
  "act.openFeed": "Abrir feed",
  "act.decide": "Decidir",
  "act.see": "Ver",
  "act.delivered": "Entregado",

  "scr.pickOne": "Elige 1 de {n} guiones",
  "scr.picked": "Elegiste {letter} · Grok prepara el board",
  "scr.recommended": "Recomendado",
  "scr.recommendedWhy": "Recomendado · {why}",
  "scr.chosen": "Elegido",
  "scr.hook": "GANCHO",
  "scr.beats": "SEGUNDO A SEGUNDO",
  "scr.allText": "Todo el texto",
  "scr.rules": "Reglas de este guion",
  "scr.pickThis": "Elegir este guion ({letter})",
  "scr.switchHint": "Ahora tienes el {letter}. Puedes cambiar hasta que Grok arme el board.",
  "scr.switchTo": "Cambiar a guion {letter}",
  "scr.clear": "Quitar elección",
  "scr.locked": "El board ya está listo con el guion {letter}.",
  "scr.sending": "Elegiste {letter} · enviando…",
  "scr.own": "Estructura propia",
  "scr.likeRef": "Como en el video de referencia",
  "scr.seeRef": "Ver video de referencia",
  "scr.format": "Formato",
  "scr.how": "Cómo",
  "scr.who": "Quién sale",
  "scr.where": "Dónde",
  "scr.duration": "Duración",
  "scr.script": "Guion {letter}",

  "prd.now": "Ahora",
  "prd.videos": "Videos",
  "prd.shop": "Ver en TikTok Shop",
  "prd.all": "Todos los productos",
  "prd.dropped": "Descartados",
  "prd.openBoard": "Abrir board",

  "mail.open": "Abrir Gmail",
  "mail.copy": "Copiar búsqueda",
  "mail.replied": "Ya respondí",
  "mail.search": "from:{from}",

  "mar.title": "Marcas",

  "grb.todo": "Por grabar",
  "grb.done": "Grabados",
  "grb.openBoard": "Abrir board",
  "grb.filmed": "Grabado",
  "grb.mark": "Marcar grabado",
  "grb.unmark": "Desmarcar",
  "grb.preparing": "Preparando",
  "grb.coming": "Board en camino",
  "grb.next": "Próxima grabación · {when}",
  "grb.progress": "{done} de {total}",
  "grb.videosReady": "{n} videos listos para grabar",

  "cre.copy": "Copiar link",
  "cre.share": "Compartir",
  "cre.more": "Más",
  "cre.extend": "Extender 3 días",
  "cre.revoke": "Revocar link",
  "cre.newLink": "Pedir link nuevo",
  "cre.review": "Revisar tomas",
  "cre.openBoard": "Ver board",
  "cre.past": "Anteriores",
  "cre.readonly": "Solo lectura. Abre el Comando para gestionar.",
  "cre.revokeTitle": "¿Revocar el link de {name}?",
  "cre.revokeBody": "Deja de funcionar al instante. Las tomas ya subidas se quedan.",
  "cre.revokeCta": "Revocar",
  "cre.hello": "Hola, {name}",

  "rev.title": "Revisar tomas",
  "rev.approve": "Aprobar",
  "rev.redo": "Re-grabar",
  "rev.redoTitle": "¿Pedir re-grabar?",
  "rev.redoHint": "Motivo (lo ve la creadora)",
  "rev.redoCta": "Pedir re-grabar",
  "rev.say": "Lo que dices",

  "brd.all": "Todos",
  "brd.guides": "Guías",
  "brd.old": "Board antiguo",
  "brd.missing": "Sin link",
  "brd.ask": "Pedir a Grok",
  "brd.ai": "Video IA",
  "brd.problem": "Con problema",
  "brd.toFilm": "Por grabar",
  "brd.editing": "Editando",
  "brd.published": "Publicados",
  "brd.retired": "Retirados",
  "brd.other": "Otros",

  "board.ref": "Video de referencia",
  "board.scenes": "Escenas",
  "board.sceneN": "Escena {n} de {total}",
  "board.refCap": "Referencia",
  "board.oursCap": "La nuestra",
  "board.script": "Guion",
  "board.copyScript": "Copiar guion",
  "board.say": "LO QUE DICES",
  "board.do": "QUÉ HACES",
  "board.play": "Toca para ver",
  "board.loadingVideo": "Cargando video…",
  "board.videoFail": "No se pudo cargar el video. Reintentar",
  "board.seeAll": "Ver todo",
  "board.leaveTitle": "Hay una subida en curso",
  "board.leaveBody": "Si sales ahora, puedes reanudar después.",
  "board.leave": "Salir",
  "board.stay": "Seguir aquí",
  "board.safe": "Zona segura 4:5",

  "por.hi": "Hola, {name}",
  "por.seeBoard": "Abrir board",
  "por.shoot": "Graba {when}",
  "por.expires": "vence {when}",
  "por.meta": "Graba {shoot} · vence {exp}",
  "por.nProducts": "{n} productos",
  "por.demo": "Demo con datos de ejemplo.",

  "fed.filters": "Filtros",
  "fed.clear": "Limpiar",
  "fed.soundOn": "Con sonido",
  "fed.soundOff": "Sin sonido",
  "fed.want": "Lo quiero",
  "fed.wanted": "Anotado",
  "fed.openTt": "Abrir en TikTok",
  "fed.score": "Score",
  "fed.window": "Ventana",
  "fed.creator": "Creador",
  "fed.updated": "Actualizado",
  "fed.all": "Todos",
  "fed.offline": "Sin conexión",
  "fed.d3": "3 días",
  "fed.d7": "7 días",
  "fed.d15": "15 días",
  "fed.d30": "30 días",

  "note.title": "Nota para Grok",
  "note.placeholder": "Un cambio, una duda…",
  "note.hint": "Grok la lee cuando le escribas. No ejecuta nada.",
  "note.send": "Enviar",
  "note.about": "Sobre: {ctx}",
  "note.discardTitle": "¿Descartar la nota?",
  "note.askNew": "Pedir link nuevo a Grok",
  "note.write": "Escribir a Grok",
  "note.askGrok": "Pedir a Grok",
  "note.askChanges": "Pedir cambios",

  "out.title": "Por enviar",
  "out.waiting": "{n} toques esperando conexión",
  "out.sending": "Enviando…",
  "out.sendNow": "Enviar ahora",
  "out.offline": "Se envía al volver la conexión.",
  "out.retry": "Reintentar",
  "out.sentToday": "Enviados hoy",
  "out.failed": "Falló",
  "out.pick": "Elegiste {letter} · {title}",
  "out.ticks": "{n} videos marcados como grabados",
  "out.want": "Lo quiero · {title}",
  "out.go": "GO · {label}",
  "out.changes": "Cambios · {label}",
  "out.note": "Nota · «{snip}»",

  "aju.theme": "Tema",
  "aju.auto": "Automático",
  "aju.light": "Claro",
  "aju.dark": "Oscuro",
  "aju.install": "Instalar en el teléfono",
  "aju.install.desktop": "Instalar en esta computadora",
  "aju.installed": "Instalada ✓",
  "aju.how": "Ver cómo",
  "aju.keys": "Llaves en este teléfono",
  "aju.keys.simple": "Llave guardada (modo simple)",
  "aju.keys.feedMissing": "Feed: falta (ábrelo una vez desde su link)",
  "aju.update": "Actualizar ahora",
  "aju.version": "Versión",
  "aju.forget": "Olvidar este teléfono",
  "aju.forgetTitle": "¿Olvidar este teléfono?",
  "aju.forgetBody": "Se borran las llaves y los datos guardados. Para volver a entrar, pega el link del Comando.",
  "aju.forgetOutbox": "Hay {n} toques sin enviar. Se pierden.",
  "aju.forgetUpload": "Hay una subida a medias.",
  "aju.forgetCta": "Olvidar",
  "aju.ok": "Comando ✓",
  "aju.feedOk": "Feed ✓",
  "aju.boardsOk": "Boards ✓",

  "ins.title": "Instala Comando",
  "ins.step1": "Toca Compartir",
  "ins.step1.other": "Toca ⋯ o Compartir",
  "ins.step2": "Toca «Agregar a inicio»",
  "ins.step3": "Abre Comando desde tu pantalla y pega tu link",
  "ins.copy": "Copiar link para la app",
  "ins.hint": "Tu link no sale de este teléfono.",
  "ins.after": "Abre Comando desde tu pantalla de inicio y pega tu link.",

  "upd.busy": "Termina la subida antes de actualizar.",

  "preview.banner": "Demo con datos de ejemplo.",

  "redir.noscript": "Activa JavaScript para abrir este link.",
};

export const COPY = STRINGS;

export function t(key, vars) {
  let s = STRINGS[key];
  if (s == null) return key;
  if (vars) {
    s = s.replace(/\{(\w+)\}/g, (_, k) => (vars[k] == null ? "" : String(vars[k])));
  }
  return s;
}

export function hasCopy(key) {
  return Object.prototype.hasOwnProperty.call(STRINGS, key);
}

export function allCopyKeys() {
  return Object.keys(STRINGS);
}

export function allCopyValues() {
  return Object.values(STRINGS);
}
